### ISSUE TITLE
control over set IDENTITY_INSERT on SQL Server

### ISSUE THREAD

**Issue by NeonRodman** [sranka/jdbc-image-tool#16]
If a table has an IDENTITY column then it always sets "IDENTITY_INSERT" to ON, expecting a value to be provided.
However, often the table in another DBMS won't have the identity column and will not have a value to provide. In this case we want IDENTITY_INSERT to be OFF.

this is causing a problem with moving data from one DBMS to SQL Server. In my case, the IDENTITY column is just there to support a cluster index as a performance improvement. The value is immaterial and is not referenced in other tables.

Either make the INSERT smart and detect if a value is provided for the column, or be able to turn the IDENTITY_INSERT ON/OFF globally as a setting during an import.

**Comment by sranka** [comment]
Thank you for posting an issue. 

You can implement a listener that does exactly what you need, see https://github.com/sranka/jdbc-image-tool/blob/master/src/main/java/pz/tool/jdbcimage/main/listener/OracleRestartGlobalSequenceListener.java for an example. I can then welcome a pull request with your implementation. Such an implementation might also require setting up tool concurrency level to `1`, since at most one table can have [IDENTITY_INSERT set to ON](https://docs.microsoft.com/en-us/sql/t-sql/statements/set-identity-insert-transact-sql?view=sql-server-ver16).

**Comment by sranka** [comment]
@NeonRodman I took a look into the code to see that identity column is already handled in https://github.com/sranka/jdbc-image-tool/blob/master/src/main/java/pz/tool/jdbcimage/main/Mssql.java#L108-L152 . Feel free to reopen this with example DB schema, test data, and a complete error message so it could be possibly reproduced.

**Comment by NeonRodman** [comment]
The example is simple:

in DB#1 (any platform)
CREATE TABLE Persons (
    SSN varchar(15) NOT NULL,
    LastName varchar(255) NOT NULL,
    FirstName varchar(255),
    Age int,
    CONSTRAINT PK_Person PRIMARY KEY (SSN,LastName)
);
Insert into Persons (SSN, LastName, FirstName, age) values('123-12-1234','Jones','Richard',25);

In DB#2 on SQL Server
CREATE TABLE Persons (
    SSN varchar(15) NOT NULL,
    LastName varchar(255) NOT NULL,
    FirstName varchar(255),
    Age int,
    int_id IDENTITY (1,1)
    CONSTRAINT PK_Person PRIMARY KEY (SSN,LastName)
);

The above is synthetic of course and you can argue its not good practice, however my real use case is very similar and quite genuine.

I have code working that handles this, but only by moving the current mssql identity code into its own optional listener and having the default listener not do anything with identity columns.

To make it ideal, it would check the metadata on the source & target tables and enable identity insertion appropriately.

**Comment by sranka** [comment]
Thank you for the instruction of how to reproduce it, it is reproducible. The import throws the following error

```
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.sql.BatchUpdateException: Explicit value must be specified for identity column in table 'Persons' either when IDENTITY_INSERT is set to ON or when a replication user is inserting into a NOT FOR REPLICATION identity column.
        at pz.tool.jdbcimage.main.MainToolBase.runConcurrently(MainToolBase.java:511)
        at pz.tool.jdbcimage.main.MainToolBase.run(MainToolBase.java:443)
        at pz.tool.jdbcimage.main.MultiTableConcurrentImport.importData(MultiTableConcurrentImport.java:191)
        at pz.tool.jdbcimage.main.MultiTableConcurrentImport.run(MultiTableConcurrentImport.java:122)
        at pz.tool.jdbcimage.main.MultiTableConcurrentImport.main(MultiTableConcurrentImport.java:200)
        at pz.tool.jdbcimage.main.JdbcImageMain.main(JdbcImageMain.java:17)
```
The actual issue is that the import executes `SET IDENTITY_INSERT [Persons] ON` even though there are no identity columns inserted.

**Comment by NeonRodman** [comment]
Just to explain why this is the case, its common practice on SQL Server to create a clustered index on a sequentially increasing column - ie an identity column. This is not typical on other DBMS platforms, it would not be unusual to copy data from a non-sql server DBMS that does not have the identity column to SQL Server where it does exist and is expected to self-populate.

**Comment by sranka** [comment]
@NeonRodman now the tool turns on identity_insert only when some data are inserted to an identity column. https://github.com/sranka/jdbc-image-tool/releases/tag/v0.8.5

**Comment by NeonRodman** [comment]
@sranka Thank you so much. I tested the fix before the release was pushed out and it is working perfectly.
awesome!
